### ISSUE TITLE
Version on extensions.gnome.org is old

### ISSUE THREAD

**Issue by ktosiek** [alexmurray/remmina-search-provider#14]
It seems the last version on https://extensions.gnome.org/extension/473/remmina-search-provider/ is 3, can you update it to the one that is currently in repo?

**Comment by alexmurray** [comment]
Sure (sadly the extensions.gnome.org mechanism for uploading new releases is a little tedious...)

**Comment by alexmurray** [comment]
Just uploaded now, waiting for review - https://extensions.gnome.org/review/6211

**Comment by alexmurray** [comment]
FYI - looks like it has been approved already.
