### ISSUE TITLE
Search overlay doesn't close when I select a result

### ISSUE THREAD

**Issue by miztroh** [alexmurray/remmina-search-provider#19]
When I search for a Remmina entry (e.g. "computerA") and then click the resulting icon, the search overlay remains open.  I then have to escape twice (once to leave the search and again to leave the activities view) to get to the Remmina window and enter my password.  I am running Arch Linux / Gnome (Wayland).  Let me know if you need any further information.  Thank you!

**Comment by miztroh** [comment]
Updating title to better reflect that the issue affects clicking a result and pressing enter on a highlighted result.

**Comment by alexmurray** [comment]
What version of gnome-shell are you running?

**Comment by miztroh** [comment]
gnome-shell --version
GNOME Shell 3.26.2

**Comment by miztroh** [comment]
I've tried this under Gnome (Xorg) as well and I get the same issue.  I have since updated to the following:

```
gnome-shell --version
GNOME Shell 3.28.0
```

**Comment by alexmurray** [comment]
Apologies for the delay in getting back to you on this - I finally got 3.28 installed and can reproduce this and am looking into it now.

**Comment by miztroh** [comment]
Anything new to report on this?

**Comment by alexmurray** [comment]
Sorry no success yet - have been sidetracked by $DAYJOB but will hopefully have a chance to look into it in the next few days.

**Comment by alexmurray** [comment]
Fixed in https://github.com/alexmurray/remmina-search-provider/commit/40995407a2b540b07dae0754a3b63d1f42c2bb90 - can you please test?

**Comment by alexmurray** [comment]
Just uploaded version 7 to extensions.gnome.org with this fix - awaiting review... https://extensions.gnome.org/review/8212
