### ISSUE TITLE
Selecting an host from overview doesn't connect to it with new options

### ISSUE THREAD

**Issue by lucamanga** [alexmurray/remmina-search-provider#21]
Hi,

when I select an host from overview it, for example, doesn't get the new screen resolution that I set in the remmina desktop.

It seems that the remmina applet copies the hosts to a custom location, so if they are modified in the remmina official client, the applet doesn't know the modifications.

**Comment by alexmurray** [comment]
@lucamanga thanks for reporting this but this sounds like it should be reported upstream to remmina as the search provider simply calls out to remmina itself to launch the given profile.
