### ISSUE TITLE
Icon missing with remmina 1.2.31

### ISSUE THREAD

**Issue by negesti** [alexmurray/remmina-search-provider#22]
After upgrading remmina today (fedora 28, remmina 1.2.31.3-1) entries in the overview no longer have an icon and are rendered with a width of ~ 4px. 

Changing the icon name in extension.js seems to fix this:  
```
 82         if (remminaApp) {
 83             icon = remminaApp.create_icon_texture(size);
 84         } else {
 85             icon = new St.Icon({ gicon: new Gio.ThemedIcon({
 86               name: 'org.remmina.Remmina'
 87             }), icon_size: size });
 88         }
```
Name was "remmina".

I'm not sure if this works with remmina < 1.2.31

**Comment by alexmurray** [comment]
Thanks for reporting this - can you try the latest version from git and see if this resolves the issue for you?

**Comment by negesti** [comment]
works like a charm

**Comment by alexmurray** [comment]
Great - I will close this issue then and push a new version to extensions.gnome.org soon.
