### ISSUE TITLE
No search results in GNOME 3.32

### ISSUE THREAD

**Issue by tsdh** [alexmurray/remmina-search-provider#23]
Since the update from GNOME 3.30 to 3.32, no remmina results are shown in the activity overview anymore.  The extension is not listed as erroneous in Tweaks, though (which is the case for several other extensions which are not yet compatible with the new GNOME release).

**Comment by alexmurray** [comment]
This should be fixed as of https://github.com/alexmurray/remmina-search-provider/commit/679e6b14917a9f978fe5b2eeb9a88cfd8c528e16 - this has also been uploaded to extensions.gnome.org as version 9 and is currently waiting review https://extensions.gnome.org/review/9541

**Comment by tsdh** [comment]
@alexmurray That was quick.  I'll report back when I've updated to the new version.

**Comment by tsdh** [comment]
@alexmurray Works again!  Thanks a lot!
