### ISSUE TITLE
icon size, gnome 3.34

### ISSUE THREAD

**Issue by petres** [alexmurray/remmina-search-provider#24]
The shown result icons are to big, they are doubled in size:
![remmina-icon-size](https://user-images.githubusercontent.com/3594062/67853801-8ec70680-fb0f-11e9-9596-d0646907b286.jpg)

I have a HIDPI screen, therefore I use scale 200%, and using the xorg session, not wayland.
Nevertheless great extension, but still hoping remmina integrates the search provider itself.
best, peter

**Comment by alexmurray** [comment]
Thanks for the report - I can reproduce this locally by setting scale to 200% in display properties so I hope to have a fix soon.

**Comment by alexmurray** [comment]
This is now fixed on master - I will release a new version (10) to extensions.gnome.org soon.
