### ISSUE TITLE
License

### ISSUE THREAD

**Issue by petres** [alexmurray/remmina-search-provider#25]
I am creating an AUR (User Arch Linux) Package for your extension, could you provide the license for this plugin, at least in your readme. Thanks!

**Comment by comradekingu** [comment]
@petres Nice, while there should be a "COPYING" or "LICENSE" file in the root repo, the actual file says GPLv2+ https://github.com/alexmurray/remmina-search-provider/blob/5adde719632534ec754bca29fdf16b44c724b962/extension.js#L9

The metadata file belongs to "Remmina Search Provider for GNOME Shell" referenced in that file, so it also gets that copyleft license.

**Comment by alexmurray** [comment]
Apologies, this issue slipped my radar - LICENSE is now added (and I updated the license to GPL3+).
