### ISSUE TITLE
In overview, ENTER has no effect

### ISSUE THREAD

**Issue by lucamanga** [alexmurray/remmina-search-provider#26]
Steps to reproduce:

1) press [WIN] or go to Overview view
2) write an host (in search results there's only one result, the host with Remmina icon)
3) press ENTER

does not produce any effects (ENTER doesn't open Remmina).

Running it on Fedora 30 and GNOME 3.32.

**Comment by alexmurray** [comment]
Is remmina installed? I can't reproduce this on GNOME 3.34 (Ubuntu 19.10)

**Comment by lucamanga** [comment]
Yes, Remmina is installed.

**Comment by lucamanga** [comment]
Now it is working.. .boh? Closing!

**Comment by alexmurray** [comment]
Feel free to reopen if it happens again and we'll see if we can debug what's going on.

**Comment by lucamanga** [comment]
Now I understood how it happens.

1) If you write the desktop name and there is only the remmina icon in results and not other (i.e. documents, characters, etc), ENTER key opens the connection with remmina.
2) If there is another result (i.e. a font name), it does not anything.
