### ISSUE TITLE
Clicking remmina connection search result doesn't open connection with GNOME 3.36

### ISSUE THREAD

**Issue by tsdh** [alexmurray/remmina-search-provider#28]
Since I've upgraded to GNOME 3.36, the remmina search provider extension isn't usable anymore.  Results show up as usual when typing in the overview, however clicking a search result with the mouse doesn't open that connection and neither does selection + return using the keyboard.  There is visual feedback, though, so it's not that the click isn't registered at all.

**Comment by Rickycezar** [comment]
```
JS ERROR: TypeError: this._resultsView is null
activate@resource:///org/gnome/shell/ui/search.js:54:9
vfunc_clicked@resource:///org/gnome/shell/ui/search.js:50:14
```

This is the error when clicking a search result

**Comment by alexmurray** [comment]
Thanks, I will try and look into this soon.

**Comment by alexmurray** [comment]
This is fixed in master and I have uploaded v12 to extensions.gnome.org - which is now awaiting review https://extensions.gnome.org/review/15277

**Comment by alexmurray** [comment]
Oh the review was already approved!

**Comment by Rickycezar** [comment]
Thanks, it solved the issue. On the same note, I think something else in the update made the results move to the bottom, after all other search providers. Based on the discussions on [#18 ](https://github.com/alexmurray/remmina-search-provider/issues/18), I assume this will be reworked as an integrated search provider in Gnome and the ordering will be made in **gnome-settings**. So I'll wait for that.
