### ISSUE TITLE
No Icon on GNOME 40 on Fedora 34

### ISSUE THREAD

**Issue by l154** [alexmurray/remmina-search-provider#31]
Hi,
Search for connection is working but there is no icon. In log I've message:
JS ERROR: TypeError: Clutter.Box is not a constructor
                                          createResultObject/metaInfo.createIcon@/home/l154/.local/share/gnome-shell/extensions/remmina-search-provider@alexmurray.github.com/extension.js:157:23
                                          _createIconTexture@resource:///org/gnome/shell/ui/iconGrid.js:136:26
                                          vfunc_style_changed@resource:///org/gnome/shell/ui/iconGrid.js:159:14
br Marcin
![image](https://user-images.githubusercontent.com/4931151/117178661-93d6d700-add2-11eb-8a12-7db8d2b7292a.png)

**Comment by alexmurray** [comment]
This should be fixed by https://github.com/alexmurray/remmina-search-provider/commit/d0290e6a10b437cd463d564571890249ade3f569

**Comment by alexmurray** [comment]
I have just uploaded a new revision to extensions.gnome.org which is waiting for approval - https://extensions.gnome.org/review/24477 - so this should be available soon.
