### ISSUE TITLE
3.14

### ISSUE THREAD

**Issue by negesti** [alexmurray/remmina-search-provider#8]
I have just update to Fedora 21 which comes with gnome-shell 3.14. Simply updating the metadata.json is not enough.

I have forked the repo und made the neccesarry changes. I don't know if my updated version would still work with 3.14. 

Really a nice extension!!

**Comment by kparal** [comment]
The change seems to be here:
https://github.com/negesti/remmina-search-provider/compare/alexmurray:master...master

Alex, could you please review and merge the changes, and then submit an updated version to extensions.gnome.org? Thanks!

**Comment by alexmurray** [comment]
3.14 is already supported now - closing.
